Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*
Metrics/MethodLength:
  Enabled: true
  Exclude: 
    - spec/stubs/*